# Generated by Django 3.0 on 2020-04-21 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='client_id',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 22, 29, 11, 687534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default='166596538', max_length=32, unique=True, verbose_name='name'),
        ),
    ]
