# Generated by Django 3.0.2 on 2020-05-02 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0002_auto_20200422_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 15, 8, 24, 606778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default='628734910', max_length=32, unique=True, verbose_name='name'),
        ),
    ]
