# Generated by Django 3.0 on 2020-05-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_area', '0005_auto_20200512_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default='374975728', max_length=32, unique=True),
        ),
    ]
